name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: ls
      run: ls -l

    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
      
    - name: install Yarn
      uses: borales/actions-yarn@v2.0.0
      with:
          cmd: install

    - name: build Yarn
      uses: borales/actions-yarn@v2.0.0
      with:
          cmd: encore production
      
    - name: ls
      run: ls -l
      
    - name: Delete node_modules
      run: sudo rm -R ./node_modules
      
    - name: ls
      run: ls -l
