name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true

    - name: Install JavaScript dependencies
      run: yarn install

    - name: Build JavaScript assets
      run: yarn encore production

    - name: zip files
      run: zip -r temp.zip . -x ".git/*" ".github/*" "node_modules/*"

    - name: ls
      run: ls -l

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "temp.zip"
        target: "temp"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: unzip temp/temp.zip -d temp