name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: ls
      run: ls -l

    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
      
    - name: check node node-version
      run: node -v

    - name: install Yarn
      run: yarn install
      
    - name: ls
      run: ls -l
      
    - name: Delete node_modules
      run: sudo rm -R ./node_modules
      
    - name: ls
      run: ls -l
